name: "Pull request compliance"
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - main

jobs:
  dco-check:
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
      - uses: tisonkun/actions-dco@v1.1
  validate-pr-title:
    name: PR Title Validation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.2.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
