name: "Pull request compliance"
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main

jobs:
  dco-check:
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
      - uses: tisonkun/actions-dco@v1.1
  conventionnal-commit:
    name: PR title and description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract pull request title
        run: echo "${{ github.event.pull_request.title }}" > pull-request-title
      - name: Check conventional commit
        run: npx git-conventional-commits commit-msg-hook pull-request-title