name: "Create PR to merge develop into main"

on:
  schedule:
    - cron: "0 10 1,15 * *"
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: develop
          title: "Merge develop into main"
          assignees: pbrissaud
          reviewers: pbrissaud